--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages =
	{
		GroupPeekPageRequest: _GroupPeekPageRequestMessage,
		GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry: _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryMessage,
		GroupPeekPageResponse: _GroupPeekPageResponseMessage,
		GroupPeekPageResponse_TemplatesEntry: _GroupPeekPageResponse_TemplatesEntryMessage,
		GroupPeekPageResponse_LocalizedLiteralsEntry: _GroupPeekPageResponse_LocalizedLiteralsEntryMessage,
	}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_client_capabilities =
	require(script.Parent.Parent.Parent.shared.v1beta1.client_capabilities)
local _roblox_apppageplatform_shared_v1beta1_hydration_content =
	require(script.Parent.Parent.Parent.shared.v1beta1.hydration_content)
local _roblox_apppageplatform_shared_v1beta1_page_entry_content =
	require(script.Parent.Parent.Parent.shared.v1beta1.page_entry_content)
local _roblox_apppageplatform_shared_v1beta1_template_entry =
	require(script.Parent.Parent.Parent.shared.v1beta1.template_entry)

type _GroupPeekPageRequestImpl = {
	__index: _GroupPeekPageRequestImpl,
	new: (fields: _GroupPeekPageRequestPartialFields?) -> GroupPeekPageRequest,
	encode: (self: GroupPeekPageRequest) -> buffer,
	decode: (input: buffer) -> GroupPeekPageRequest,
	jsonEncode: (self: GroupPeekPageRequest) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> GroupPeekPageRequest,
	descriptor: proto.Descriptor,
}

type _GroupPeekPageRequestFields = {
	group_id: string,
	client_capabilities: _roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities?,
	cached_roblox_component_to_template_id: { [string]: string },
}

type _GroupPeekPageRequestPartialFields = {
	group_id: string?,
	client_capabilities: _roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities?,
	cached_roblox_component_to_template_id: { [string]: string }?,
}

export type GroupPeekPageRequest = typeof(setmetatable(
	{} :: _GroupPeekPageRequestFields,
	{} :: _GroupPeekPageRequestImpl
))
type _GroupPeekPageRequestMessage = proto.Message<GroupPeekPageRequest, _GroupPeekPageRequestPartialFields>

type _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl = {
	__index: _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl,
	new: (
		fields: _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryPartialFields?
	) -> GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry,
	encode: (self: GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry) -> buffer,
	decode: (input: buffer) -> GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry,
	jsonEncode: (self: GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry,
	descriptor: proto.Descriptor,
}

type _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryFields = {
	key: string,
	value: string,
}

type _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryPartialFields = {
	key: string?,
	value: string?,
}

export type GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry = typeof(setmetatable(
	{} :: _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryFields,
	{} :: _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl
))
type _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryMessage = proto.Message<
	GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry,
	_GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryPartialFields
>

type _GroupPeekPageResponseImpl = {
	__index: _GroupPeekPageResponseImpl,
	new: (fields: _GroupPeekPageResponsePartialFields?) -> GroupPeekPageResponse,
	encode: (self: GroupPeekPageResponse) -> buffer,
	decode: (input: buffer) -> GroupPeekPageResponse,
	jsonEncode: (self: GroupPeekPageResponse) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> GroupPeekPageResponse,
	descriptor: proto.Descriptor,
}

type _GroupPeekPageResponseFields = {
	page_entries: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry },
	hydration_data: _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent?,
	templates: { [string]: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry },
	localized_literals: { [string]: string },
}

type _GroupPeekPageResponsePartialFields = {
	page_entries: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry }?,
	hydration_data: _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent?,
	templates: { [string]: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry }?,
	localized_literals: { [string]: string }?,
}

export type GroupPeekPageResponse = typeof(setmetatable(
	{} :: _GroupPeekPageResponseFields,
	{} :: _GroupPeekPageResponseImpl
))
type _GroupPeekPageResponseMessage = proto.Message<GroupPeekPageResponse, _GroupPeekPageResponsePartialFields>

type _GroupPeekPageResponse_TemplatesEntryImpl = {
	__index: _GroupPeekPageResponse_TemplatesEntryImpl,
	new: (fields: _GroupPeekPageResponse_TemplatesEntryPartialFields?) -> GroupPeekPageResponse_TemplatesEntry,
	encode: (self: GroupPeekPageResponse_TemplatesEntry) -> buffer,
	decode: (input: buffer) -> GroupPeekPageResponse_TemplatesEntry,
	jsonEncode: (self: GroupPeekPageResponse_TemplatesEntry) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> GroupPeekPageResponse_TemplatesEntry,
	descriptor: proto.Descriptor,
}

type _GroupPeekPageResponse_TemplatesEntryFields = {
	key: string,
	value: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry?,
}

type _GroupPeekPageResponse_TemplatesEntryPartialFields = {
	key: string?,
	value: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry?,
}

export type GroupPeekPageResponse_TemplatesEntry = typeof(setmetatable(
	{} :: _GroupPeekPageResponse_TemplatesEntryFields,
	{} :: _GroupPeekPageResponse_TemplatesEntryImpl
))
type _GroupPeekPageResponse_TemplatesEntryMessage = proto.Message<
	GroupPeekPageResponse_TemplatesEntry,
	_GroupPeekPageResponse_TemplatesEntryPartialFields
>

type _GroupPeekPageResponse_LocalizedLiteralsEntryImpl = {
	__index: _GroupPeekPageResponse_LocalizedLiteralsEntryImpl,
	new: (
		fields: _GroupPeekPageResponse_LocalizedLiteralsEntryPartialFields?
	) -> GroupPeekPageResponse_LocalizedLiteralsEntry,
	encode: (self: GroupPeekPageResponse_LocalizedLiteralsEntry) -> buffer,
	decode: (input: buffer) -> GroupPeekPageResponse_LocalizedLiteralsEntry,
	jsonEncode: (self: GroupPeekPageResponse_LocalizedLiteralsEntry) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> GroupPeekPageResponse_LocalizedLiteralsEntry,
	descriptor: proto.Descriptor,
}

type _GroupPeekPageResponse_LocalizedLiteralsEntryFields = {
	key: string,
	value: string,
}

type _GroupPeekPageResponse_LocalizedLiteralsEntryPartialFields = {
	key: string?,
	value: string?,
}

export type GroupPeekPageResponse_LocalizedLiteralsEntry = typeof(setmetatable(
	{} :: _GroupPeekPageResponse_LocalizedLiteralsEntryFields,
	{} :: _GroupPeekPageResponse_LocalizedLiteralsEntryImpl
))
type _GroupPeekPageResponse_LocalizedLiteralsEntryMessage = proto.Message<
	GroupPeekPageResponse_LocalizedLiteralsEntry,
	_GroupPeekPageResponse_LocalizedLiteralsEntryPartialFields
>

do
	local _GroupPeekPageRequestImpl = {}
	_GroupPeekPageRequestImpl.__index = _GroupPeekPageRequestImpl

	function _GroupPeekPageRequestImpl.new(data: _GroupPeekPageRequestPartialFields?): GroupPeekPageRequest
		return setmetatable({
			group_id = if data == nil or data.group_id == nil then "" else data.group_id,
			client_capabilities = if data == nil or data.client_capabilities == nil
				then nil
				else data.client_capabilities,
			cached_roblox_component_to_template_id = if data == nil
					or data.cached_roblox_component_to_template_id == nil
				then {}
				else data.cached_roblox_component_to_template_id,
		}, _GroupPeekPageRequestImpl :: _GroupPeekPageRequestImpl)
	end

	function _GroupPeekPageRequestImpl.encode(self: GroupPeekPageRequest): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.group_id ~= nil and self.group_id ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.group_id)
		end

		if self.client_capabilities ~= nil then
			local encoded = self.client_capabilities:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if
			self.cached_roblox_component_to_template_id ~= nil
			and next(self.cached_roblox_component_to_template_id) ~= nil
		then
			for key, value in self.cached_roblox_component_to_template_id do
				local mapBuffer = buffer.create(0)
				local mapCursor = 0
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 1, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, key)
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 2, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, value)
				output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, mapBuffer, mapCursor)
			end
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _GroupPeekPageRequestImpl.decode(input: buffer): GroupPeekPageRequest
		local self = _GroupPeekPageRequestImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.group_id = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.client_capabilities =
						_roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)

					local mapEntry = messages.GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry.decode(value)

					local keyDefault = ""
					local valueDefault = ""

					self.cached_roblox_component_to_template_id[mapEntry.key or keyDefault] = mapEntry.value
						or valueDefault

					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _GroupPeekPageRequestImpl.jsonEncode(self: GroupPeekPageRequest): any
		local output = {}

		if self.group_id ~= nil and self.group_id ~= "" then
			output.groupId = self.group_id
		end

		if self.client_capabilities ~= nil then
			output.clientCapabilities = self.client_capabilities:jsonEncode()
		end

		if
			self.cached_roblox_component_to_template_id ~= nil
			and next(self.cached_roblox_component_to_template_id) ~= nil
		then
			local newOutput = {}
			for key, value in self.cached_roblox_component_to_template_id do
				newOutput[key] = value
			end
			output.cachedRobloxComponentToTemplateId = newOutput
		end

		return output
	end

	function _GroupPeekPageRequestImpl.jsonDecode(input: { [string]: any }): GroupPeekPageRequest
		local self = _GroupPeekPageRequestImpl.new()

		if input.group_id ~= nil then
			self.group_id = input.group_id
		end

		if input.groupId ~= nil then
			self.group_id = input.groupId
		end

		if input.client_capabilities ~= nil then
			self.client_capabilities =
				_roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities.jsonDecode(
					input.client_capabilities
				)
		end

		if input.clientCapabilities ~= nil then
			self.client_capabilities =
				_roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities.jsonDecode(
					input.clientCapabilities
				)
		end

		if input.cached_roblox_component_to_template_id ~= nil then
			local newOutput: { [string]: string } = {}
			for key, value in input.cached_roblox_component_to_template_id do
				newOutput[key] = value
			end

			self.cached_roblox_component_to_template_id = newOutput
		end

		if input.cachedRobloxComponentToTemplateId ~= nil then
			local newOutput: { [string]: string } = {}
			for key, value in input.cachedRobloxComponentToTemplateId do
				newOutput[key] = value
			end

			self.cached_roblox_component_to_template_id = newOutput
		end

		return self
	end

	_GroupPeekPageRequestImpl.descriptor = {
		name = "GroupPeekPageRequest",
		fullName = "roblox.apppageplatform.groups.v1beta1.GroupPeekPageRequest",
	}

	messages.GroupPeekPageRequest = _GroupPeekPageRequestImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.GroupPeekPageRequest)
end

do
	local _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl = {}
	_GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.__index =
		_GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl

	function _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.new(
		data: _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryPartialFields?
	): GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry
		return setmetatable(
			{
				key = if data == nil or data.key == nil then "" else data.key,
				value = if data == nil or data.value == nil then "" else data.value,
			},
			_GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl :: _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl
		)
	end

	function _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.encode(
		self: GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry
	): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.key ~= nil and self.key ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.key)
		end

		if self.value ~= nil and self.value ~= "" then
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.value)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.decode(
		input: buffer
	): GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry
		local self = _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.key = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.value = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.jsonEncode(
		self: GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry
	): any
		local output = {}

		if self.key ~= nil and self.key ~= "" then
			output.key = self.key
		end

		if self.value ~= nil and self.value ~= "" then
			output.value = self.value
		end

		return output
	end

	function _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.jsonDecode(
		input: { [string]: any }
	): GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry
		local self = _GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.new()

		if input.key ~= nil then
			self.key = input.key
		end

		if input.value ~= nil then
			self.value = input.value
		end

		return self
	end

	_GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.descriptor = {
		name = "GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry",
		fullName = "roblox.apppageplatform.groups.v1beta1.CachedRobloxComponentToTemplateIdEntry",
	}

	messages.GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry =
		_GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntryImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.GroupPeekPageRequest_CachedRobloxComponentToTemplateIdEntry)
end

do
	local _GroupPeekPageResponseImpl = {}
	_GroupPeekPageResponseImpl.__index = _GroupPeekPageResponseImpl

	function _GroupPeekPageResponseImpl.new(data: _GroupPeekPageResponsePartialFields?): GroupPeekPageResponse
		return setmetatable({
			page_entries = if data == nil or data.page_entries == nil then {} else data.page_entries,
			hydration_data = if data == nil or data.hydration_data == nil then nil else data.hydration_data,
			templates = if data == nil or data.templates == nil then {} else data.templates,
			localized_literals = if data == nil or data.localized_literals == nil then {} else data.localized_literals,
		}, _GroupPeekPageResponseImpl :: _GroupPeekPageResponseImpl)
	end

	function _GroupPeekPageResponseImpl.encode(self: GroupPeekPageResponse): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.page_entries ~= nil and #self.page_entries > 0 then
			for _, value in self.page_entries do
				local encoded = value:encode()
				output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			end
		end

		if self.hydration_data ~= nil then
			local encoded = self.hydration_data:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.templates ~= nil and next(self.templates) ~= nil then
			for key, value in self.templates do
				local mapBuffer = buffer.create(0)
				local mapCursor = 0
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 1, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, key)
				local encoded = value:encode()
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 2, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeBuffer(mapBuffer, mapCursor, encoded, buffer.len(encoded))
				output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, mapBuffer, mapCursor)
			end
		end

		if self.localized_literals ~= nil and next(self.localized_literals) ~= nil then
			for key, value in self.localized_literals do
				local mapBuffer = buffer.create(0)
				local mapCursor = 0
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 1, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, key)
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 2, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, value)
				output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, mapBuffer, mapCursor)
			end
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _GroupPeekPageResponseImpl.decode(input: buffer): GroupPeekPageResponse
		local self = _GroupPeekPageResponseImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					table.insert(
						self.page_entries,
						_roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry.decode(value)
					)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.hydration_data =
						_roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)

					local mapEntry = messages.GroupPeekPageResponse_TemplatesEntry.decode(value)

					local keyDefault = ""
					local valueDefault = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.new()

					self.templates[mapEntry.key or keyDefault] = mapEntry.value or valueDefault

					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)

					local mapEntry = messages.GroupPeekPageResponse_LocalizedLiteralsEntry.decode(value)

					local keyDefault = ""
					local valueDefault = ""

					self.localized_literals[mapEntry.key or keyDefault] = mapEntry.value or valueDefault

					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _GroupPeekPageResponseImpl.jsonEncode(self: GroupPeekPageResponse): any
		local output = {}

		if self.page_entries ~= nil and #self.page_entries > 0 then
			local newOutput = {}
			for _, value in self.page_entries do
				table.insert(newOutput, value:jsonEncode())
			end
			output.pageEntries = newOutput
		end

		if self.hydration_data ~= nil then
			output.hydrationData = self.hydration_data:jsonEncode()
		end

		if self.templates ~= nil and next(self.templates) ~= nil then
			local newOutput = {}
			for key, value in self.templates do
				newOutput[key] = value:jsonEncode()
			end
			output.templates = newOutput
		end

		if self.localized_literals ~= nil and next(self.localized_literals) ~= nil then
			local newOutput = {}
			for key, value in self.localized_literals do
				newOutput[key] = value
			end
			output.localizedLiterals = newOutput
		end

		return output
	end

	function _GroupPeekPageResponseImpl.jsonDecode(input: { [string]: any }): GroupPeekPageResponse
		local self = _GroupPeekPageResponseImpl.new()

		if input.page_entries ~= nil then
			local newOutput: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry } = {}
			for _, value in input.page_entries do
				table.insert(
					newOutput,
					_roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry.jsonDecode(value)
				)
			end

			self.page_entries = newOutput
		end

		if input.pageEntries ~= nil then
			local newOutput: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry } = {}
			for _, value in input.pageEntries do
				table.insert(
					newOutput,
					_roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry.jsonDecode(value)
				)
			end

			self.page_entries = newOutput
		end

		if input.hydration_data ~= nil then
			self.hydration_data = _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent.jsonDecode(
				input.hydration_data
			)
		end

		if input.hydrationData ~= nil then
			self.hydration_data = _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent.jsonDecode(
				input.hydrationData
			)
		end

		if input.templates ~= nil then
			local newOutput: { [string]: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry } = {}
			for key, value in input.templates do
				newOutput[key] = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.jsonDecode(value)
			end

			self.templates = newOutput
		end

		if input.localized_literals ~= nil then
			local newOutput: { [string]: string } = {}
			for key, value in input.localized_literals do
				newOutput[key] = value
			end

			self.localized_literals = newOutput
		end

		if input.localizedLiterals ~= nil then
			local newOutput: { [string]: string } = {}
			for key, value in input.localizedLiterals do
				newOutput[key] = value
			end

			self.localized_literals = newOutput
		end

		return self
	end

	_GroupPeekPageResponseImpl.descriptor = {
		name = "GroupPeekPageResponse",
		fullName = "roblox.apppageplatform.groups.v1beta1.GroupPeekPageResponse",
	}

	messages.GroupPeekPageResponse = _GroupPeekPageResponseImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.GroupPeekPageResponse)
end

do
	local _GroupPeekPageResponse_TemplatesEntryImpl = {}
	_GroupPeekPageResponse_TemplatesEntryImpl.__index = _GroupPeekPageResponse_TemplatesEntryImpl

	function _GroupPeekPageResponse_TemplatesEntryImpl.new(
		data: _GroupPeekPageResponse_TemplatesEntryPartialFields?
	): GroupPeekPageResponse_TemplatesEntry
		return setmetatable({
			key = if data == nil or data.key == nil then "" else data.key,
			value = if data == nil or data.value == nil then nil else data.value,
		}, _GroupPeekPageResponse_TemplatesEntryImpl :: _GroupPeekPageResponse_TemplatesEntryImpl)
	end

	function _GroupPeekPageResponse_TemplatesEntryImpl.encode(self: GroupPeekPageResponse_TemplatesEntry): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.key ~= nil and self.key ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.key)
		end

		if self.value ~= nil then
			local encoded = self.value:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _GroupPeekPageResponse_TemplatesEntryImpl.decode(input: buffer): GroupPeekPageResponse_TemplatesEntry
		local self = _GroupPeekPageResponse_TemplatesEntryImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.key = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.value = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _GroupPeekPageResponse_TemplatesEntryImpl.jsonEncode(self: GroupPeekPageResponse_TemplatesEntry): any
		local output = {}

		if self.key ~= nil and self.key ~= "" then
			output.key = self.key
		end

		if self.value ~= nil then
			output.value = self.value:jsonEncode()
		end

		return output
	end

	function _GroupPeekPageResponse_TemplatesEntryImpl.jsonDecode(
		input: { [string]: any }
	): GroupPeekPageResponse_TemplatesEntry
		local self = _GroupPeekPageResponse_TemplatesEntryImpl.new()

		if input.key ~= nil then
			self.key = input.key
		end

		if input.value ~= nil then
			self.value = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.jsonDecode(input.value)
		end

		return self
	end

	_GroupPeekPageResponse_TemplatesEntryImpl.descriptor = {
		name = "GroupPeekPageResponse_TemplatesEntry",
		fullName = "roblox.apppageplatform.groups.v1beta1.TemplatesEntry",
	}

	messages.GroupPeekPageResponse_TemplatesEntry = _GroupPeekPageResponse_TemplatesEntryImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.GroupPeekPageResponse_TemplatesEntry)
end

do
	local _GroupPeekPageResponse_LocalizedLiteralsEntryImpl = {}
	_GroupPeekPageResponse_LocalizedLiteralsEntryImpl.__index = _GroupPeekPageResponse_LocalizedLiteralsEntryImpl

	function _GroupPeekPageResponse_LocalizedLiteralsEntryImpl.new(
		data: _GroupPeekPageResponse_LocalizedLiteralsEntryPartialFields?
	): GroupPeekPageResponse_LocalizedLiteralsEntry
		return setmetatable({
			key = if data == nil or data.key == nil then "" else data.key,
			value = if data == nil or data.value == nil then "" else data.value,
		}, _GroupPeekPageResponse_LocalizedLiteralsEntryImpl :: _GroupPeekPageResponse_LocalizedLiteralsEntryImpl)
	end

	function _GroupPeekPageResponse_LocalizedLiteralsEntryImpl.encode(
		self: GroupPeekPageResponse_LocalizedLiteralsEntry
	): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.key ~= nil and self.key ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.key)
		end

		if self.value ~= nil and self.value ~= "" then
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.value)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _GroupPeekPageResponse_LocalizedLiteralsEntryImpl.decode(
		input: buffer
	): GroupPeekPageResponse_LocalizedLiteralsEntry
		local self = _GroupPeekPageResponse_LocalizedLiteralsEntryImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.key = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.value = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _GroupPeekPageResponse_LocalizedLiteralsEntryImpl.jsonEncode(
		self: GroupPeekPageResponse_LocalizedLiteralsEntry
	): any
		local output = {}

		if self.key ~= nil and self.key ~= "" then
			output.key = self.key
		end

		if self.value ~= nil and self.value ~= "" then
			output.value = self.value
		end

		return output
	end

	function _GroupPeekPageResponse_LocalizedLiteralsEntryImpl.jsonDecode(
		input: { [string]: any }
	): GroupPeekPageResponse_LocalizedLiteralsEntry
		local self = _GroupPeekPageResponse_LocalizedLiteralsEntryImpl.new()

		if input.key ~= nil then
			self.key = input.key
		end

		if input.value ~= nil then
			self.value = input.value
		end

		return self
	end

	_GroupPeekPageResponse_LocalizedLiteralsEntryImpl.descriptor = {
		name = "GroupPeekPageResponse_LocalizedLiteralsEntry",
		fullName = "roblox.apppageplatform.groups.v1beta1.LocalizedLiteralsEntry",
	}

	messages.GroupPeekPageResponse_LocalizedLiteralsEntry = _GroupPeekPageResponse_LocalizedLiteralsEntryImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.GroupPeekPageResponse_LocalizedLiteralsEntry)
end

return {
	GroupPeekPageRequest = messages.GroupPeekPageRequest,
	GroupPeekPageResponse = messages.GroupPeekPageResponse,
}
