-- Auto-generated by service-contracts. DO NOT EDIT MANUALLY.

local proto = require(script.Parent.Parent.Parent.Parent.proto)
export type Descriptor = proto.Descriptor
export type Message<T, Fields> = proto.Package<T, Fields>
export type CustomJson<T, Json> = proto.CustomJson<T, Json>
export type TypeRegistry = proto.TypeRegistry

local group_peek_page = require(script.group_peek_page)

-- Exported types
export type GroupPeekPageRequest = group_peek_page.GroupPeekPageRequest
export type GroupPeekPageResponse = group_peek_page.GroupPeekPageResponse

return {
	group_peek_page = group_peek_page,
}
